import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomePage from '@/components/Home'
import Navbar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  console.log(data)
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>{data.title}</h1>
     <HomePage data={data} />
      <div>

      </div>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('data/data.json');
  console.log("hello")
  return {
    props: {
      data: events_categories,
    },
  };
}
